name = "The Finest Creations"
author = "Treeway7"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38d53689f1a7a60e8dc88f6eab9102fde1354b6894874a2f4a9be44e4788cdc8"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
