name = "The Finest Creations"
author = "Treeway7"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6988e7a2c6e3af33965c5acac3b452bad2f185c60469324f57905746b68414c"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
