name = "The Finest Creations"
author = "Treeway7"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6992c9f63f7ce016bc41e54de53869ac15e23031c845b6dc14f4195cb0ca937"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
datapack-folder = "global_packs/required_data"
