name = "The Finest Creations"
author = "Treeway7"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a82550a5bfdeca5eb3590af27d062de31e80d692c8ccf441255ad2fb15d40e7"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
