name = "The Finest Creations"
author = "Treeway7"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77385fbe143c69103d70267c1917c1518da7e8a06804b29d105de54ce7806f82"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
