name = "The Finest Creations"
author = "Treeway7"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15974f6840fe66b3eb9f343a54feaba26a66e80eb1bc78af0d263461d53fc834"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
