name = "The Finest Creations"
author = "Treeway7"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e159ee1c0f0a0852556a43737c6cd2906dde27d170a72f751c3cd0f6ea691d39"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
