name = "The Finest Creations"
author = "Treeway7"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e64716554254e7fa92cabb0e820831241aaad8e4c51f1f31b09a6414d27e82e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
