name = "The Finest Creations"
author = "Treeway7"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ede09b923570252d54332884b7eb839d41346af916f7fdaa925359f471023043"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
