name = "The Finest Creations"
author = "Treeway7"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2f71ca957e2b00c4e87bdd6f0f4b1b93e634f4d731100a26bca8c6a582dc8ba"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
