name = "The Finest Creations"
author = "Treeway7"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "189b1a4d845d0c7a2e02cb9c5db2b591fc107a4e9004b78005c035eb0c606c8a"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
