name = "The Finest Creations"
author = "Treeway7"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af998ede0a9b3604dacf1b6188f5649724be7649fd6caa8efa161983a28cc0ce"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
